server:
  port: 8088

spring:
  application:
    name: RATING-SERVICE

  config:
    import: "configserver:http://localhost:8092"

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Z_Microservices

  profiles:
    active: test
